@localhost = http://localhost:3000

@renderlink = https://cse341-projects-kl.onrender.com/

###LOCALHOST Get Home Page -- 
GET {{{{localhost}}}}

###LOCALHOST Get all users
GET {{{{localhost}}}}/users

###LOCALHOST Get contact by id
GET {{{{localhost}}}}/users/65068ed3ce661403440a872a

###LOCALHOST Create Contact
POST {{{{localhost}}}}/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "TestFName",
    "lastName": "TestLName",
    "email": "testemail@test.com",
    "favoriteColor": "purple",
    "birthday": "5/9/2006"
}

###LOCALHOST Update Contact -- change whatever element below that you need to change
PUT {{{{localhost}}}}/users/65068ed3ce661403440a872a HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "janedoe@aol.com",
    "favoriteColor": "Red",
    "birthday": "1/2/1975"
}

###LOCALHOST DELETE Contact -- change id to whatever you need to delete
DELETE {{{{localhost}}}}/users/<IDHERETODELETE>

// Render Link
###RENDERLINK Get Home Page -- 
GET {{{{renderlink}}}}

###RENDERLINK Get all users
GET {{{{renderlink}}}}/users

###RENDERLINK Get contact by id
GET {{{{renderlink}}}}/users/65068ed3ce661403440a872a

###RENDERLINK Create Contact
POST {{{{renderlink}}}}/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "TestFName",
    "lastName": "TestLName",
    "email": "testemail@test.com",
    "favoriteColor": "purple",
    "birthday": "5/9/2006"
}

###RENDERLINK Update Contact -- change whatever element below that you need to change
PUT {{{{renderlink}}}}/users/65068ed3ce661403440a872a HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "janedoe@aol.com",
    "favoriteColor": "Red",
    "birthday": "1/2/1975"
}

###RENDERLINK DELETE Contact -- change id to whatever you need to delete
DELETE {{{{renderlink}}}}/users/<IDHERETODELETE>